# // mô tả api
# // POST   http://localhost:3000/api/auth/register
# // Phương thức: post, get, path, put, delete
# // đường dẫn api:  http://localhost:3000/api/auth/register
# // header: Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibnZzYW5nLjE4aXQyQHNpY3QudWRuLnZuIiwiaWF0IjoxNjQ5OTE0NzcxfQ.X80_vc1FeVa1mJZWDnGcweWsMabtx_p3IoySUfkjAE8
# // -> kiểm tra token
# // header: Content-Type: application/json
# // -> nhập vào body api với nội dung là json
# // header: Content-Type: multipart/form-data
# // -> truyền file vào trong body
# #### đường dẫn kho lưu trữ
# http://localhost:3000/uploads/avatars/avatar_defaul.png

###Register
POST   http://localhost:3000/api/auth/register
Content-Type: application/json

{ 
    "email" : "nvsang.18it2@sict.udn.vn",
    "password" : "123456789",
    "username" : "sang 79",
    "confirmPassword": "123456789"
}

###Logout
GET   http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibnZzYW5nLjE4aXQyQHNpY3QudWRuLnZuIiwiaWF0IjoxNjQ5OTE0NzcxfQ.X80_vc1FeVa1mJZWDnGcweWsMabtx_p3IoySUfkjAE8

###Login
POST   http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email" : "nvsang.18it2@sict.udn.vn",
    "password" : "123456789"
}

###Get profile
GET   http://localhost:3000/api/user/profile/627a93e30cba03b9fb8e84bf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibnZzYW5nLjE4aXQyQHNpY3QudWRuLnZuIiwiaWF0IjoxNjUyMjAyMTUyfQ.amIPNPyQfvq2xviVe-v-cjVqqGMmoqKygy5RHCZrZP4

###
POST   http://localhost:3000/api/user/profile/627f710f2c16c1efd18689d9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI3ZjcxMGYyYzE2YzFlZmQxODY4OWQ5IiwiaWF0IjoxNjUyNTE5MTgzfQ.uqR20FRYaG8AB4yjzGJW8tJMCNbetAagmZUnnZwvaZo
Content-Type: application/json

{
    "username" : "nguyễn văn sang",
    "about" : "um ba la chap",
    "address" : "06 nam ki khoi nghia",
    "birthday" : "26-07-2000",
    "gender" : 0
}

###// 0 là nữ, 1 là nam
###
PATCH http://localhost:3000/api/user/upload-avatar/627a93e30cba03b9fb8e84bf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibnZzYW5nLjE4aXQyQGdtYWlsLmNvbSIsImlhdCI6MTYzNTQ3OTg2Mn0.jwmxmgyKUcjb7eaSPQw0khAkssatj_linzSsKuvieMQ
Content-Type: multipart/form-data
{
    "upload_avatar": "file"
}

###
PATCH http://localhost:3000/api/user/upload-cover/627a93e30cba03b9fb8e84bf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibnZzYW5nLjE4aXQyQGdtYWlsLmNvbSIsImlhdCI6MTYzNTQ3OTg2Mn0.jwmxmgyKUcjb7eaSPQw0khAkssatj_linzSsKuvieMQ
Content-Type: multipart/form-data
{
    "upload_cover": "file"
}