http://localhost:3000/uploads/avatars/avatar_defaul.png
###Register
POST   http://localhost:3000/api/auth/register
Content-Type: application/json

{ 
    "email" : "nvsang.18it2@sict.udn.vn",
    "password" : "123456789",
    "username" : "sang 79",
    "confirmPassword": "123456789"
}

###Logout
GET   http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibnZzYW5nLjE4aXQyQHNpY3QudWRuLnZuIiwiaWF0IjoxNjQ5OTE0NzcxfQ.X80_vc1FeVa1mJZWDnGcweWsMabtx_p3IoySUfkjAE8

###Login
POST   http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email" : "nvsang.18it2@sict.udn.vn",
    "password" : "123456789"
}

###Get profile
GET   http://localhost:3000/api/user/profile/627a93e30cba03b9fb8e84bf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibnZzYW5nLjE4aXQyQHNpY3QudWRuLnZuIiwiaWF0IjoxNjUyMjAyMTUyfQ.amIPNPyQfvq2xviVe-v-cjVqqGMmoqKygy5RHCZrZP4

###
POST   http://localhost:3000/api/user/profile/627a93e30cba03b9fb8e84bf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibnZzYW5nLjE4aXQyQGdtYWlsLmNvbSIsImlhdCI6MTYzNTQ3OTg2Mn0.jwmxmgyKUcjb7eaSPQw0khAkssatj_linzSsKuvieMQ
Content-Type: application/json

{
    "username" : "nguyễn văn sang",
    "about" : "123456789",
    "address" : "06 nam ki khoi nghia",
    "birthday" : "26-07-2000",
    "avatar" : "",
    "cover" : ""
}

###
PATCH http://localhost:3000/api/user/upload-avatar/627a93e30cba03b9fb8e84bf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibnZzYW5nLjE4aXQyQGdtYWlsLmNvbSIsImlhdCI6MTYzNTQ3OTg2Mn0.jwmxmgyKUcjb7eaSPQw0khAkssatj_linzSsKuvieMQ